import sys
sys.path.append("C:\\Users\\matse\\gig\\src\\system_v5") # Adjust this path to point to the root of your project if needed

import numpy as np
import json
from sentence_transformers import SentenceTransformer
from sklearn.cluster import AgglomerativeClustering
from agent_loop.agents.ontology_cleanup.resolve_classes_agent import ResolveClassesAgent
from backends import load_backend
import argparse

def load_classes_from_ontology(ontology_path: str, num_chunks: int = None) -> list:
    """
    Extracts classes from a given ontology structure.
    
    Args:
        ontology_path (str): The path to the ontology file.
        num_chunks (int): The number of chunks to consider. If None, considers all chunks. This is useful for testing with a subset of the ontology.
        
    Returns:
        list: A list of class dictionaries, e.g., [{"id": "ClassA", "description": "..."}]
    """
    with open(ontology_path, 'r', encoding='utf-8') as f:
        ontology = json.load(f)

    # check if ontology was loaded successfully
    if "ontology_tbox" not in ontology or "classes" not in ontology["ontology_tbox"]:
        print("Error: Ontology structure is invalid. 'ontology_tbox' or 'classes' key is missing.")
        return []
    print("Ontology loaded successfully. Extracting classes...")

    if num_chunks is not None:
        # Filter classes to only include those from the specified number of chunks
        ontology["ontology_tbox"]["classes"] = [c for c in ontology["ontology_tbox"]["classes"] if c.get("chunk_ids") and int(c["chunk_ids"][0]) < num_chunks]

    classes = []
    for cls in ontology["ontology_tbox"]["classes"]:
        if cls["chunk_ids"]: # avoiding the base ontology classes which have empty chunk_id
            cls_id = cls.get("id", "").strip()
            cls_desc = cls.get("description", "").strip()
            if cls_id:
                classes.append({"id": cls_id, "description": cls_desc})
    
    print(f"Extracted {len(classes)} classes from the ontology.")
    return classes

def cluster_classes(classes: list, threshold: float = 0.30) -> list:
    """
    Clusters ontology classes based on the semantic similarity of their names and descriptions.
    
    Args:
        classes (list): A list of dictionaries, e.g., [{"id": "ClassA", "description": "..."}]
        threshold (float): Distance threshold for clustering (1.0 - cosine_similarity). 
                           Lower = stricter clusters (e.g., 0.30 = 70% similarity).
        
    Returns:
        list: A list of clusters, where each cluster is a list of class dictionaries.
    """
    if not classes:
        return []
        
    print("Loading embedding model (all-MiniLM-L6-v2)...")
    # all-MiniLM-L6-v2 is an extremely fast, tiny 80MB model specifically designed for semantic clustering
    model = SentenceTransformer('all-MiniLM-L6-v2')
    
    print(f"Embedding {len(classes)} classes...")
    # Combine the ID and description to get a rich semantic representation
    texts_to_embed = [f"{c.get('id', '')}: {c.get('description', '')}" for c in classes]
    embeddings = model.encode(texts_to_embed)
    
    print("Clustering classes...")
    # We use Agglomerative Clustering because we don't know the final number of clusters upfront
    clustering_model = AgglomerativeClustering(
        n_clusters=None, 
        distance_threshold=threshold, 
        metric='cosine', 
        linkage='average'
    )
    clustering_model.fit(embeddings)
    
    # Group classes by their assigned cluster labels
    clusters = {}
    for idx, label in enumerate(clustering_model.labels_):
        if label not in clusters:
            clusters[label] = []
        clusters[label].append(classes[idx])
        
    print(f"Formed {len(clusters)} clusters out of {len(classes)} classes.")
    return list(clusters.values())

def generate_equivalence_axioms(alias_map: dict):
    equivalences = []
    
    # First, append the generic schema definition for equivalentClass
    equivalences.append({
        "type": "equivalentClass",
        "domains": ["Entity"],
        "ranges": ["Entity"],
        "description": "States that two classes are semantically identical and share the exact same instances."
    })
    
    # Then, append the specific class-to-class equivalences mapped by the agent
    for original_id, canonical_id in alias_map.items():
        # Skip if the class was chosen as the canonical one
        if original_id == canonical_id:
            continue
            
        # Create an axiom matching the TBox schema structure
        equivalences.append({
            "type": "equivalentClass",
            "domains": [original_id],
            "ranges": [canonical_id],
            "description": f"Generated by Entity Resolution: '{original_id}' is semantically equivalent to '{canonical_id}'."
        })
        
    return equivalences

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--backend", default="phi-npu-openvino") # decides which backend to use here.
    args = parser.parse_args()

    backend = load_backend(name=args.backend)
    ontology_path = "C:\\Users\\matse\\gig\\src\\system_v5\\intermediate_results\\phi-npu-openvino_ontology_20260406_232546.json"

    # Load classes from the ontology and cluster them
    classes = load_classes_from_ontology(ontology_path)#, num_chunks=20)
    print(f"Loaded {len(classes)} classes from ontology for all chunks.")
    clustered_classes = cluster_classes(classes)
    actual_clusters = [c for c in clustered_classes if len(c) > 1]
    print(f"Actual clusters (with more than 1 class): {len(actual_clusters)}")
    
    # Resolve clusters with the ResolveClassesAgent
    resolve_agent = ResolveClassesAgent(backend=backend) # Pass the appropriate backend if needed
    print("Resolving clusters with ResolveClassesAgent...")
    alias_map = {}
    for cluster in actual_clusters[:5]: # Limit to first 5 clusters for testing
        print(f"--- Cluster {actual_clusters.index(cluster)+1}/{len(actual_clusters)} ---")
        resolutions, _ = resolve_agent.run(cluster)
        for res in resolutions:
            alias_map[res["original_id"]] = res["canonical_id"]
            # Save or update your master global canonical definitions here as well
    print(f"Resolved {len(alias_map)} classes into canonical forms.")
    print("resolved classes:")
    for original_id, canonical_id in alias_map.items():
        print(f"  {original_id} -> {canonical_id}")
    
    # Generate equivalence axioms based on the alias map
    equivalence_axioms = generate_equivalence_axioms(alias_map)
    print(f"Generated {len(equivalence_axioms)} equivalence axioms based on resolved classes.")

    # append these new axioms to the existing ontology TBox and save the updated ontology

if __name__ == "__main__":
    main()