"""
Regenerate gold_answer_agent and gold_mapped_answer for the ontology-grounded dataset.

1. gold_answer_agent: Natural answer plus reasoning
2. gold_mapped_answer: Generated by simulating map_answer_to_context()
"""

import sys
sys.path.append("C:\\Users\\matse\\gig\\src\\system_v5")

import json
from rdflib import Graph, RDFS, RDF, OWL, URIRef, Literal
from urllib.parse import unquote
import re
import difflib
from typing import Dict, Any, List

# Import pipeline utilities
from tools.ttl_handling.load_ttl import load_ttl
from tools.ttl_handling.resolve_ttl_path import resolve_ttl_path
from tools.inference_module.fetch_relevant_info import retrieve_full_entity_context, retrieve_top_candidates
from tools.inference_module.map_answer_to_context import map_answer_to_context as pipeline_map_answer_to_context

# ============================================================================
# Load dataset and graph
# ============================================================================

print("Loading dataset...")
with open("tests/dataset/ontology_grounded_100.json", "r") as f:
    dataset = json.load(f)

print("Loading TTL...")
ttl_path = resolve_ttl_path()
ttl_result = load_ttl(ttl_path)
graph = ttl_result["graph"]
print(f"TTL loaded: {len(graph)} triples")

# ============================================================================
# Helper functions
# ============================================================================

def normalize(text: str) -> str:
    """Lowercase, strip, collapse whitespace."""
    return re.sub(r"\s+", " ", text.lower().strip())

def get_entity_uri(graph, entity_name: str):
    """Resolve entity name to URI using top-candidate matching."""
    candidates = retrieve_top_candidates(graph, entity_name, top_n=1)
    if candidates:
        return candidates[0]["uri"]
    return None

def get_entity_context(entity_name: str, graph) -> Dict[str, Any]:
    """Retrieve full entity context from TTL."""
    candidates = retrieve_top_candidates(graph, entity_name, top_n=1)
    if not candidates:
        print(f"  WARNING: Could not find entity '{entity_name}'")
        return None
    
    entity = candidates[0]
    context = retrieve_full_entity_context(entity, graph)
    return context

def formulate_answer_with_evidence(item: Dict[str, Any], context: Dict[str, Any]) -> str:
    """
    Formulate a natural sentence answer with evidence based on question type and context.
    """
    question_type = item.get("question_type", "")
    answer_form = item.get("answer_form", "")
    atomic_input = item.get("atomic_input", "")
    
    # Extract from flat structure
    entity_dict = item.get("entity", {})
    entity = entity_dict.get("value", "") if isinstance(entity_dict, dict) else entity_dict
    
    relation = item.get("relation", "")
    object_dict = item.get("object", {})
    obj = object_dict.get("value", "") if isinstance(object_dict, dict) else object_dict
    
    if not context:
        return "I can't answer the question"
    
    # DEFINITION: "What is X?" → "X is a [type/class]"
    if question_type == "definition":
        types_list = context.get("types", [])
        eq_classes = context.get("equivalent_classes", [])
        
        # Prefer types over equivalent classes for definitions
        if types_list:
            primary_type = types_list[0]
            evidence = f"is a {primary_type}"
            if len(types_list) > 1:
                others = ", ".join(types_list[1:])
                evidence += f" (also {others})"
            return f"{entity} {evidence}."
        elif eq_classes:
            return f"{entity} is equivalent to {eq_classes[0]}."
        else:
            return "I can't answer the question"
    
    # TAXONOMIC/ASSERTION: "Is X a Y?" → "yes" or "no" based on types/superclasses
    elif question_type == "taxonomic" and answer_form == "assertion":
        if not obj:
            return "I can't answer the question"
        
        types_list = context.get("types", [])
        superclasses_by_type = context.get("superclasses", {})
        all_superclasses = []
        for sc_list in superclasses_by_type.values():
            all_superclasses.extend(sc_list)
        
        obj_norm = normalize(obj)
        match_found = False
        matching_class = None
        
        # Check if obj matches any type or superclass
        for t in types_list:
            if normalize(t) == obj_norm or normalize(t).startswith(obj_norm) or obj_norm in normalize(t):
                match_found = True
                matching_class = t
                break
        
        if not match_found:
            for sc in all_superclasses:
                if normalize(sc) == obj_norm or normalize(sc).startswith(obj_norm) or obj_norm in normalize(sc):
                    match_found = True
                    matching_class = sc
                    break
        
        if match_found:
            if matching_class:
                return f"Yes, {entity} is a {matching_class}."
            else:
                return f"Yes, {entity} is a {obj}."
        else:
            return f"No, {entity} is not a {obj}."
    
    # CAPABILITY: "Does X have Y?" → "Yes, X has Y" or describe the capability
    elif question_type == "capability":
        # Look for the capability in properties/values or as a type
        types_list = context.get("types", [])
        properties_by_type = context.get("properties_by_type", {})
        
        capability_name = None
        
        # Check in properties
        for t, pdata in properties_by_type.items():
            for item in pdata.get("outgoing_object_properties", []):
                prop = normalize(item.get("property", ""))
                value = normalize(item.get("object", ""))
                if "capability" in prop or "capability" in value:
                    capability_name = item.get("object", "")
                    break
        
        if capability_name:
            return f"{entity} has the capability {capability_name}."
        else:
            return "I can't answer the question"
    
    # PROPERTY: "What is the [property] of X?" → "The [property] of X is [value]"
    elif question_type == "property":
        properties_by_type = context.get("properties_by_type", {})
        prop_name_normalized = normalize(relation) if relation else ""
        
        found_value = None
        for t, pdata in properties_by_type.items():
            for item in pdata.get("outgoing_object_properties", []):
                if normalize(item.get("property", "")) == prop_name_normalized:
                    found_value = item.get("object", "")
                    break
            
            if found_value:
                break
            
            for item in pdata.get("outgoing_data_properties", []):
                if normalize(item.get("property", "")) == prop_name_normalized:
                    found_value = str(item.get("value", ""))
                    break
            
            if found_value:
                break
        
        if found_value:
            return f"The {relation} of {entity} is {found_value}."
        else:
            return "I can't answer the question"
    
    # MEMBERSHIP: "Is X a member of Y?" or "What are members of X?"
    elif question_type == "membership":
        if answer_form == "assertion":
            # "Is X a member of Y?"
            # Check hasMember, hasPart, etc.
            properties_by_type = context.get("properties_by_type", {})
            is_member = False
            
            for t, pdata in properties_by_type.items():
                for item in pdata.get("incoming_object_properties", []):
                    if "member" in normalize(item.get("property", "")):
                        is_member = True
                        break
            
            return "Yes" if is_member else "No"
        else:
            # "What are members of X?" → list
            properties_by_type = context.get("properties_by_type", {})
            members = []
            
            for t, pdata in properties_by_type.items():
                for item in pdata.get("outgoing_object_properties", []):
                    if "member" in normalize(item.get("property", "")):
                        members.append(item.get("object", ""))
            
            if members:
                return ", ".join(members)
            else:
                return "I can't answer the question"
    
    # QUANTIFICATION: "How many X?" → "N"
    elif question_type == "quantification":
        # Count something - for now return "I can't answer"
        return "I can't answer the question"
    
    # EXISTENTIAL: "Does X exist?" or "Is there an X?"
    elif question_type == "existential":
        # Should be answerable by checking if entity was resolved
        return "Yes" if context else "No"
    
    # COMPARATIVE: "Is X more Y than Z?"
    elif question_type == "comparative":
        return "I can't answer the question"
    
    return "I can't answer the question"

# ============================================================================
# Main regeneration loop
# ============================================================================

print("\nRegenerating answers and mappings...")
updated_count = 0
error_count = 0

for idx, item in enumerate(dataset):
    item_id = item.get("id", idx)
    
    if idx % 10 == 0:
        print(f"Processing item {idx+1}/100...")
    
    try:
        # Skip items marked as absent (not answerable)
        ontology_presence = item.get("ontology_presence", "")
        
        if ontology_presence == "absent":
            # For absent items, keep "I can't answer the question"
            item["gold_answer_agent"] = {
                "reasoning": "No supporting ontology facts were found for the entity.",
                "answer": "I can't answer the question."
            }
            item["gold_mapped_answer"] = {
                "entity_side": {
                    "types": [],
                    "superclasses": [],
                    "equivalent_classes": [],
                    "properties": [],
                    "property_values": {}
                }
            }
            continue
        
        # Get entity name from flat structure
        entity_dict = item.get("entity", {})
        entity_name = entity_dict.get("value", "") if isinstance(entity_dict, dict) else entity_dict
        
        if not entity_name:
            print(f"  {item_id}: No entity found")
            error_count += 1
            continue
        
        # Retrieve entity context
        context = get_entity_context(entity_name, graph)
        
        if not context:
            print(f"  {item_id}: Could not find context for {entity_name}")
            error_count += 1
            continue
        
        # Generate evidence-based answer
        gold_answer = formulate_answer_with_evidence(item, context)
        
        # Simulate map_answer_to_context
        mapped = pipeline_map_answer_to_context(gold_answer, context)
        
        # Update item
        item["gold_answer_agent"] = {
            "reasoning": f"The ontology evidence supports the answer: {gold_answer}",
            "answer": gold_answer
        }
        item["gold_mapped_answer"] = {
            "entity_side": mapped
        }
        
        updated_count += 1
        
    except Exception as e:
        print(f"  {item_id}: Error - {str(e)}")
        error_count += 1
        continue

print(f"\nCompleted: {updated_count} items updated, {error_count} errors")

# ============================================================================
# Save updated dataset
# ============================================================================

print("\nSaving updated dataset...")
with open("tests/dataset/ontology_grounded_100.json", "w") as f:
    json.dump(dataset, f, indent=2)

print("✓ Saved ontology_grounded_100.json")

# Synchronize natural version
print("\nSynchronizing natural version...")
with open("tests/dataset/ontology_grounded_100_natural.json", "r") as f:
    natural_dataset = json.load(f)

# Keep natural questions, update answers and mappings
for nat_item, orig_item in zip(natural_dataset, dataset):
    nat_item["gold_answer_agent"] = orig_item["gold_answer_agent"]
    nat_item["gold_mapped_answer"] = orig_item["gold_mapped_answer"]

with open("tests/dataset/ontology_grounded_100_natural.json", "w") as f:
    json.dump(natural_dataset, f, indent=2)

print("✓ Saved ontology_grounded_100_natural.json")

print("\n✅ Regeneration complete!")
