import sys
sys.path.append("C:\\Users\\matse\\gig\\src\\system_v5") # Adjust this path to point to the root of your project if needed

import argparse
from backends import load_backend

from agent_loop.agents.inference_module.validate_answer_agent import ValidateAnswerAgent

# validation agent inputs:
# - atomic question: the original input question in atomic format
# - question-type (and description?)
# - Extracted triplet (entity, relation, object)
# - generated answer: the answer generated by the GenerateAnswerAgent
# - mapped answer: the answer mapped back to the ontology context by the MapToContextAgent
def clean_and_prepare_mapped_answer_triplets(entity_value: str, mapped_answer: dict) -> dict:
    # removes empty fields and standardizes the format of the mapped answer for easier processing by the validation agent
    cleaned_answer = []
    if not mapped_answer:
        return cleaned_answer
    for key, value in mapped_answer.items():
        if value:
            if key == "types" or key == "superclasses" or key == "equivalent_classes":
                for v in value:
                    cleaned_answer.append({"entity": entity_value, "relation": "be", "object": v}) # ensure entity value is included in the mapped answer for validation
            elif key == "property_values":
                for prop, val in value.items():
                    cleaned_answer.append({"entity": entity_value, "relation": prop, "object": val}) # ensure entity value is included in the mapped answer for validation
    return cleaned_answer

def validate_answer(answer: dict, question_info: dict, relevant_info: dict, mapped_answer: dict, validate_answer_agent: ValidateAnswerAgent = None) -> bool:
    #0. unpack inputs
    atomic_question = question_info.get("atomic_question")
    question_type = question_info.get("question_type")
    extracted_triplet_values = {"entity": question_info.get("entity").get("value"),
                         "relation": question_info.get("relation"),
                         "object": question_info.get("object").get("value")}
    entity_value = question_info.get("entity").get("value")
    generated_answer = answer.get("answer")
    mapped_answer_triplets = clean_and_prepare_mapped_answer_triplets(entity_value, mapped_answer)
    print("================================")
    print("atomic question:", atomic_question)
    print(f"Question type: {question_type}")
    print(f"Extracted triplet: {extracted_triplet_values}")
    print(f"Generated answer: {generated_answer}")
    print(f"Mapped answer triplets: {mapped_answer_triplets}")
    print("================================")

    if validate_answer_agent is None:
        # 1. Initialize backend and agents
        backend = load_backend(name="phi-npu-openvino")
        validate_answer_agent = ValidateAnswerAgent(backend=backend)

    # 2. Run validation agent with the above inputs and return validation result
    validation_result, _ = validate_answer_agent.run(atomic_question=atomic_question,
                                                  question_type=question_type,
                                                  extracted_triplet=extracted_triplet_values,
                                                  generated_answer=generated_answer,
                                                  mapped_answer_triplets=mapped_answer_triplets)
    
    print(f"Validation result: {validation_result}")
    return validation_result.get("decision")
